### ISSUE TITLE
因文章編輯後格式錯誤 造成無法解析的清況

### ISSUE THREAD

**Issue by et84121** [Truth0906/PTTLibrary#39]
也許需要為這種情況做點調整？

### Test Code
```python
"Place module docstring here"
import os
from PTTLibrary import PTT

PTT_BOT = PTT.Library(
    # 目前支援繁體中文與英文
    # (預設值) Chinese
    # Language=PTT.Language.Chinese,
    # Language=PTT.Language.English,
    # 有三個等級可以選擇
    # (預設值) INFO
    # LogLevel=PTT.LogLevel.INFO,
    LogLevel=PTT.LogLevel.TRACE,
    # LogLevel=PTT.LogLevel.DEBUG,
)
try:
    PTT_BOT.login(
        os.getenv('PTT_USER_NAME', 'PTT_USER_NAME Not found'),
        os.getenv('PTT_USER_PASSWORD', 'PTT_USER_PASSWORD Not found'),
        KickOtherLogin=False
    )
except PTT.Exceptions.LoginError:
    PTT_BOT.log('登入失敗')
PTT_BOT.log('登入成功')

board = 'Steam'

Post = PTT_BOT.getPost(
    board,
    #PostIndex=PTT_BOT.getNewestIndex(PTT.IndexType.Board, Board=board)
    PostIndex=4444
)

print(Post.getTitle())


PTT_BOT.logout()

```

### 該篇文章截圖
![image](https://user-images.githubusercontent.com/9102619/63654918-b0281100-c7b3-11e9-98c5-d4efdacee301.png)

文章代碼(AID): #17VB5YVd (Steam) [ptt.cc] [公告] C-Strike 板 開始賭博!  
文章網址: https://www.ptt.cc/bbs/Steam/M.1199354210.A.7E7.html     

### Trace Information
```bash
PTT Library v 0.8.10
Developed by PTT CodingMan
[0826 03:37:53][資訊] 繁體中文語言模組 [初始化]
[0826 03:37:53][資訊] 連線核心 [初始化]
[0826 03:37:53][資訊] 批踢踢函式庫 v 0.8.10 [初始化]
[0826 03:37:53][資訊] 登入帳號 [et84121]
[0826 03:37:53][資訊] 連線核心 [啟動]
[0826 03:37:53][資訊] 連線批踢踢 [WebSocket]
[0826 03:37:53][除錯] 送出訊息 !!!you can't see me!!!
--------------------------------------------------
HTTP/1.1 200 OK

     ˙      PTT                   ◣          ˙      ◢██████◤
             140.112.172.11      ◢█◥█◤            ◢█████
  ┌─┐     批踢踢實業坊        ◢▃██◥█◤      ◢█████◤
  │–└┐   ptt.cc            ◢█████◥█◤    ◢█████
  │–  │                   ◢███◤███◥◤  ◢█████◤  ˙
─┘    │┌──┐         ◥◤      ████◣◢████
        └┤  –│                 ◢████◢███◤
                │┌───┐         █████▇▇▆▆▅▅▄▄▃▂▁
            ┌─┴┘––  └ ◢█████▇▇▆▆▅▅▄▄▃▃▂▂▁
            │––           ◥██
len:496
--------------------------------------------------
--------------------------------------------------















                                                        撐香港的自由


       歡迎來到 批踢踢實業坊 目前有【47893】位使用者


 ※本站目前暫停開放新帳號註冊。
=PTT=[21;1H
len:145
--------------------------------------------------
--------------------------------------------------















                                                        撐香港的自由


       歡迎來到 批踢踢實業坊 目前有【47893】位使用者


 ※本站目前暫停開放新帳號註冊。
=PTT=[21;1H

len:145
--------------------------------------------------
--------------------------------------------------






















 登入中，請稍候...
len:33
--------------------------------------------------
[0826 03:37:53][資訊] 批踢踢訊息 [登入中，請稍候]
[0826 03:37:53][除錯] 花費時間 [0.12]
[0826 03:37:53][除錯] 送出訊息 [b'\x0c']
--------------------------------------------------





















 注意: 您有其它連線已登入此帳號。
您想刪除其他重複登入的連線嗎？[Y/n]
len:64
--------------------------------------------------
[0826 03:37:53][資訊] 批踢踢訊息 [不剔除其他登入]
[0826 03:37:53][除錯] 花費時間 [0.3]
[0826 03:37:53][除錯] 送出訊息 [b'n\r\x0c']
--------------------------------------------------





















 注意: 您有其它連線已登入此帳號。
您想刪除其他重複登入的連線嗎？[Y/n]
len:64
--------------------------------------------------
[0826 03:37:53][資訊] 批踢踢訊息 [不剔除其他登入]
[0826 03:37:53][除錯] 花費時間 [0.02]
[0826 03:37:53][除錯] 送出訊息 [b'n\r\x0c']
--------------------------------------------------
                                              活動看板   PttFamous
   j  ㄨ  p         ▁▂▃▄    ▄▃▃▄▅g       獺獺獺獺◤▎
 ㄐ銵c─cμ     o ▂▄▆v▍  v▆g ▔￣       ▊▌        哄▏◢
 ◤c▃▄▃c◣ Ｐ   p df ▎ e▅  ▅e    ▉        ▊de
◤ ●﹒● ◣Ｔ =PTT=[0;36;4
len:244
--------------------------------------------------
--------------------------------------------------
                                              活動看板   PttFamous
   j  ㄨ  p         ▁▂▃▄    ▄▃▃▄▅g       獺獺獺獺◤▎
 ㄐ銵c─cμ     o ▂▄▆v▍  v▆g ▔￣       ▊▌        哄▏◢
 ◤c▃▄▃c◣ Ｐ   p df ▎ e▅  ▅e    ▉        ▊de
◤ ●﹒● ◣Ｔ o eg ◣l▏ l▍  〓                  j  〓n ▏   ▍ ◣      k okk
    ︶︶    Ｔ  pkdf k▏   d▃▃▄f▁   m ▎◣ ◣   deo▌oj
    " "'      oo   p◣j   ◤b ▂▃▃▄g  ▍   ◣ ◣ fg   ok j
   首獎300,000P      ▋▁▂芍f  =PTT=[0
len:429
--------------------------------------------------
--------------------------------------------------
                                              活動看板   PttFamous  
   j  ㄨ  p         ▁▂▃▄    ▄▃▃▄▅g       獺獺獺獺◤▎
 ㄐ銵c─cμ     o ▂▄▆v▍  v▆g ▔￣       ▊▌        哄▏◢
 ◤c▃▄▃c◣ Ｐ   p df ▎ e▅  ▅e    ▉        ▊de
◤ ●﹒● ◣Ｔ o eg ◣l▏ l▍  〓                  j  〓n ▏   ▍ ◣      k okk
    ︶︶    Ｔ  pkdf k▏   d▃▃▄f▁   m ▎◣ ◣   deo▌oj
    " "'      oo   p◣j   ◤b ▂▃▃▄g  ▍   ◣ ◣ fg   ok j
   首獎300,000P      ▋▁▂芍f   ▅▆▁◥   ◣      ◣                             v▍
                                                          ＿＿＿＿
                         b                               活動看板  FamousWords
      ◣  ▁ ◢▁c  df▃▄▅     ▔       獺獺獺獺  ◣▍◤
      ◥▂ d▄f  ◤  ▅▆▔   ▂▃ 縑    c▁▎▂▄f   ◤  c一c_
  Ｐ   v ◤間◣    ◤縈d▄▅▆ e▄▅ ▄ ▅m   ▂c e▅v  f=PTT=[4
len:770
--------------------------------------------------
--------------------------------------------------
                                              活動看板   PttFamous
   j  ㄨ  p         ▁▂▃▄    ▄▃▃▄▅g       獺獺獺獺◤▎
 ㄐ銵c─cμ     o ▂▄▆v▍  v▆g ▔￣       ▊▌        哄▏◢
 ◤c▃▄▃c◣ Ｐ   p df ▎ e▅  ▅e    ▉        ▊de
◤ ●﹒● ◣Ｔ o eg ◣l▏ l▍  〓                  j  〓n ▏   ▍ ◣      k okk
    ︶︶    Ｔ  pkdf k▏   d▃▃▄f▁   m ▎◣ ◣   deo▌oj
    " "'      oo   p◣j   ◤b ▂▃▃▄g  ▍   ◣ ◣ fg   ok j
   首獎300,000P      ▋▁▂芍f   ▅▆▁◥   ◣      ◣                             v▍
                                                          ＿＿＿＿
                         b                               活動看板  FamousWords
      ◣  ▁ ◢▁c  df▃▄▅     ▔       獺獺獺獺  ◣▍◤
      ◥▂ d▄f  ◤  ▅▆▔   ▂▃ 縑    c▁▎▂▄f   ◤  c一c_
  Ｐ   v ◤間◣    ◤縈d▄▅▆ e▄▅ ▄ ▅m   ▂c e▅v  fe▄▅▆
  Ｔ ◣▇ ▂e  ◤  ▄▅ ▍  e▄▅v▔    o ◣        ◢▂▂▃
  Ｔ   v j  ▍ 岷▍      m   c▃  f▄▅     ▍  ◣ ◣     m ▂▂▃ ▋
     ◤ okl▎   l▍   p m  oo   ▏  ▍   ◣ ◣    ▂▂▃ ▊
    ◤▊▌▏g ▎▍   ▊ ▌  g▉=PTT=[0;
len:953
--------------------------------------------------
--------------------------------------------------
                                              活動看板   PttFamous
   j  ㄨ  p         ▁▂▃▄    ▄▃▃▄▅g       獺獺獺獺◤▎
 ㄐ銵c─cμ     o ▂▄▆v▍  v▆g ▔￣       ▊▌        哄▏◢
 ◤c▃▄▃c◣ Ｐ   p df ▎ e▅  ▅e    ▉        ▊de
◤ ●﹒● ◣Ｔ o eg ◣l▏ l▍  〓                  j  〓n ▏   ▍ ◣      k okk
    ︶︶    Ｔ  pkdf k▏   d▃▃▄f▁   m ▎◣ ◣   deo▌oj
    " "'      oo   p◣j   ◤b ▂▃▃▄g  ▍   ◣ ◣ fg   ok j
   首獎300,000P      ▋▁▂芍f   ▅▆▁◥   ◣      ◣                             v▍
                                                          ＿＿＿＿
                         b                               活動看板  FamousWords
      ◣  ▁ ◢▁c  df▃▄▅     ▔       獺獺獺獺  ◣▍◤
      ◥▂ d▄f  ◤  ▅▆▔   ▂▃ 縑    c▁▎▂▄f   ◤  c一c_
  Ｐ   v ◤間◣    ◤縈d▄▅▆ e▄▅ ▄ ▅m   ▂c e▅v  fe▄▅▆
  Ｔ ◣▇ ▂e  ◤  ▄▅ ▍  e▄▅v▔    o ◣        ◢▂▂▃
  Ｔ   v j  ▍ 岷▍      m   c▃  f▄▅     ▍  ◣ ◣     m ▂▂▃ ▋
     ◤ okl▎   l▍   p m  oo   ▏  ▍   ◣ ◣    ▂▂▃ ▊
    ◤▊▌▏g ▎▍   ▊ ▌  g▉g▇ ▎       ◣   縈▔◣
                            ￣


       歡迎您再度拜訪，上次您是從 1.170.141.195 連往本站。


 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
len:1131
--------------------------------------------------
[0826 03:37:54][資訊] 批踢踢訊息 [請按任意鍵繼續]
[0826 03:37:54][除錯] 花費時間 [0.87]
[0826 03:37:54][除錯] 送出訊息 [b'q']
--------------------------------------------------
【主功能表】                     批踢踢實業坊
███████████████████████████████████████
▅▆▆◥███████████████████████████████████
     -─`     ￣￣￣      ￣￣￣    ￣￣                  ￣￣￣￣￣￣
            ▂▃     ︱       ｜        ﹨     ｜     \                   ∣
 \_   ∕ ◤▂ ▊。   /  ∕  ﹍ ﹨  L_         |        |  ⊥       ｜   .∠
   ╳    ▊˙▎◤▎`┐ │,   ︳▁   ╓-.︿   ∕  ` _︳ ∣ .  _x_    \   ｜ ╲
 L  _▄▊\ ▆'     N ＼_7_︷-+┤ ↖╳   〉┬'┌‵√ 7╴.-！′   `┬+┼=.∕= ╴
┤ ▄ ▄, ╲,_  ◢│\_╱▏\_∕_﹀  _;}—L  ↘_〕-_╳  |   ＼__F ↙  ﹍] ▏_∕
 ╲=PTT=[32
len:543
--------------------------------------------------
--------------------------------------------------
【主功能表】                     批踢踢實業坊
███████████████████████████████████████
▅▆▆◥███████████████████████████████████
     -─`     ￣￣￣      ￣￣￣    ￣￣                  ￣￣￣￣￣￣
            ▂▃     ︱       ｜        ﹨     ｜     \                   ∣
 \_   ∕ ◤▂ ▊。   /  ∕  ﹍ ﹨  L_         |        |  ⊥       ｜   .∠
   ╳    ▊˙▎◤▎`┐ │,   ︳▁   ╓-.︿   ∕  ` _︳ ∣ .  _x_    \   ｜ ╲
 L  _▄▊\ ▆'     N ＼_7_︷-+┤ ↖╳   〉┬'┌‵√ 7╴.-！′   `┬+┼=.∕= ╴
┤ ▄ ▄, ╲,_  ◢│\_╱▏\_∕_﹀  _;}—L  ↘_〕-_╳  |   ＼__F ↙  ﹍] ▏_∕
 ╲r▎◥〃└_▄〞↗╳ ▕_ ┘╳ ╲_↙▎↙↑_▕  ,┼▕  ﹨  ﹀`  ▎`￣  ↖￣} ╲
 r┘ ▄ ◥▃▆┬╝└ ▎  ╲ ` ▏├  ￣\  ’︺▏可不可以偶爾下雨不必永遠晴天...

───────── 上方為使用者心情點播留言區，不代表本站立場 ────────
                       (A)nnounce     【 精華公佈欄 】
                       (F)avorite     【 我 的 最愛 】
                     > (C)lass        【 分組討論區 】
                       (M)ail         【 私人信件區 】
                       (T)alk         【 休閒聊天區 】
                       (U)ser         【 個人設定區 】
                       (X)yz          【 系統資訊區 】
                       (P)lay         【 娛樂與休閒 】
                       (N)amelist     【 編特別名單 】
                       (G)oodbye         離開，再見…
[8/26 星期一 3:37] [ 金牛時 ]    線上47893人, 我是et84121         [呼叫器]打開

len:1242
--------------------------------------------------
[0826 03:37:54][資訊] 批踢踢訊息 [登入成功]
[0826 03:37:54][除錯] 花費時間 [0.05]
[0826 03:37:54][資訊] 登入成功
[0826 03:37:54][除錯] 送出訊息 [b' \x1bOD\x1bOD\x1bOD\x1bOD\x1bODqsSteam\r\x03\x03 1\r$\x0c']
--------------------------------------------------
【板主:hn9480412/flyingwhale/LonyIce】本板禁止徵求買賣合購代購代刷
[←]離開 [→]閱讀 [Ctrl-P]發表文章 [d]刪除 [z]精華區 [i]看板資訊/設定 [h]說明
   編號    日 期 作  者       文  章  標  題                         人氣:218
   54326 +爆 8/25 Soaz          □ [閒聊] G胖在上海
   54327 + 2 8/25 yoseii       □ [心得] Life is strange 2 第四章 很多劇透
   54328 +24 8/25 cain1187     □ [CSGO] 實況主fl0m因轉播Berlin Major被Ban台
   54329 +19 8/25 power907     □ [問題] MHW的接待員貓咪造型可以關掉嗎
   54330 +85 8/25 yrs1224      □ [CSGO] S-L Berlin Major 2019 挑戰者組 Day 3
   54331 + 5 8/25 LisaGi       □ [心得] Wanna Survive 活屍戰棋
   54332     8/25 becausemusic R: [問題] 找兩款很久以前的遊戲
   54333     8/25 -            □ (本文已被刪除) [chi1206]
   54334   4 8/25 alanalg      □ [限免] Winexy (indiegala)
   543
len:712
--------------------------------------------------
--------------------------------------------------
【板主:hn9480412/flyingwhale/LonyIce】本板禁止徵求買賣合購代購代刷
[←]離開 [→]閱讀 [Ctrl-P]發表文章 [d]刪除 [z]精華區 [i]看板資訊/設定 [h]說明
   編號    日 期 作  者       文  章  標  題                         人氣:218
   54326 +爆 8/25 Soaz          □ [閒聊] G胖在上海
   54327 + 2 8/25 yoseii       □ [心得] Life is strange 2 第四章 很多劇透
   54328 +24 8/25 cain1187     □ [CSGO] 實況主fl0m因轉播Berlin Major被Ban台
   54329 +19 8/25 power907     □ [問題] MHW的接待員貓咪造型可以關掉嗎
   54330 +85 8/25 yrs1224      □ [CSGO] S-L Berlin Major 2019 挑戰者組 Day 3
   54331 + 5 8/25 LisaGi       □ [心得] Wanna Survive 活屍戰棋
   54332     8/25 becausemusic R: [問題] 找兩款很久以前的遊戲
   54333     8/25 -            □ (本文已被刪除) [chi1206]
   54334   4 8/25 alanalg      □ [限免] Winexy (indiegala)
   54335  15 8/25 jakert123    R: [情報] 《逆轉裁判123成步堂精選集》中文化確定
   54336  12 8/25 cain1187     □ [Dota] Ti9 OG完成二連霸
   54337 +18 8/25 Raidensnake  □ [問題] stardew valley星露谷老婆的選擇
   54338 +10 8/25 YOYOISGOOD   □ [問題] 關於雙手把 正廠和副廠可以共用嗎?
   54339     8/25 st12231      □ [實況] 空洞騎士 格林劇團開演【美哥】
   54340   2 8/25 aad784900    □ [問題] 請問有類似「電影夢工場」的遊戲嗎
   54341 +   8/26 aaronshell   □ [閒聊] Titanfall 2 戰役真的短到嚇到(但超好玩R
     ★   爆 5/30 flyingwhale  □ [公告] 板務宣導/置底聊天區
     ★  m 5 9/15 flyingwhale  □ [公告] Steam板板規/文章推薦區
     ★  !   6/01 hn9480412    □ [公告] 交易文章使用說明(發文/推文前請詳閱)
>   ★   40 8/01 hn9480412    □ [公告] 8月置底遊戲交換區
 文章選讀  (y)=PTT=[3
len:1328
--------------------------------------------------
[0826 03:37:54][除錯] 批踢踢訊息 [成功]
[0826 03:37:54][除錯] 花費時間 [0.05]
[0826 03:37:54][除錯] 找到最新編號 [54341]
[0826 03:37:54][除錯] 送出訊息 [b' \x1bOD\x1bOD\x1bOD\x1bOD\x1bODqsSteam\r\x03\x03 4444\rQ\x0c']
--------------------------------------------------
0m回應(X)推文(^X)轉錄 (=[]<>)相關主題(/?a)找標題/作者 (b)進板畫面






















len:71
--------------------------------------------------
--------------------------------------------------
【板主:hn9480412/flyingwhale/LonyIce】本板禁止徵求買賣合購代購代刷
[←]離開 [→]閱讀 [Ctrl-P]發表文章 [d]刪除 [z]精華區 [i]看板資訊/設定 [h]說明
   編號    日 期 作  者       文  章  標  題                         人氣:218
   4434 m   1/01 zop          R: 有玩ＴＦＣ２的來自介一下吧
   4435 m   1/01 tn703678     R: 有玩ＴＦＣ２的來自介一下吧
   4436  98 1/01 Siu          □ [建議] 來寫2008年ID對照表吧XD
   4437     1/01 onlyforu     □ [問題] kode5 demo
   4438 m 2 1/02 QuakeRz      □ [情報] ESA兩岸三地交流資格賽 首場台灣vs大陸
   4439 m 3 1/02 amgdaaaa     □ [ＸＤ] ＴＦ２無用小常識分享
   4440   6 1/02 cs80506      □ [買賣]Plantronics GAMECOM_PRO1 USB 專業耳麥
   4441   3 1/02 Star123      □ [閒聊] 怎麼都沒人......
   4442 m   1/02 sgouki       R: 有玩ＴＦＣ２的來自介一下吧

>  4444   6 1/03
len:838
--------------------------------------------------
--------------------------------------------------
【板主:hn9480412/flyingwhale/LonyIce】本板禁止徵求買賣合購代購代刷
[←]離開 [→]閱讀 [Ctrl-P]發表文章 [d]刪除 [z]精華區 [i]看板資訊/設定 [h]說明
   編號    日 期 作  者       文  章  標  題                         人氣:218
   4434 m   1/01 zop          R: 有玩ＴＦＣ２的來自介一下吧
   4435 m   1/01 tn703678     R: 有玩ＴＦＣ２的來自介一下吧
   4436  98 1/01 Siu          □ [建議] 來寫2008年ID對照表吧XD
   4437     1/01 onlyforu     □ [問題] kode5 demo
   4438 m 2 1/02 QuakeRz      □ [情報] ESA兩岸三地交流資格賽 首場台灣vs大陸
   4439 m 3 1/02 amgdaaaa     □ [ＸＤ] ＴＦ２無用小常識分享
   4440   6 1/02 cs80506      □ [買賣]Plantronics GAMECOM_PRO1 USB 專業耳麥
   4441   3 1/02 Star123      □ [閒聊] 怎麼都沒人......
   4442 m   1/02 sgouki       R: 有玩ＴＦＣ２的來自介一下吧

>  4444   6 1/03 Siu          □ [公告] C-Strike 板 開始賭博!
┌─────────────────────────────────────┐
│ 文章代碼(AID): #17VB5YVd (Steam) [ptt.cc] [公告] C-Strike 板 開始賭博!   │
│ 文章網址: https://www.ptt.cc/bbs/Steam/M.1199354210.A.7E7.html                 │
│ 這一篇文章值 0 Ptt幣                                                              │
└─────────────────────────────────────┘

   4451 m 1 1/04 How0428      R: 有玩ＴＦＣ２的來自介一下吧
   4452   4 1/04 nrevols      □ [心得]被[ＢＡ]server ban了
   4453   2 1/04 Siu          □ [建議] 請按[V]投票
 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
len:1458
--------------------------------------------------
[0826 03:37:54][除錯] 批踢踢訊息 [取得文章成功]
[0826 03:37:54][除錯] 花費時間 [0.04]
[0826 03:37:54][除錯] PostAID [17VB5YVd]
[0826 03:37:54][除錯] PostWeb [https://www.ptt.cc/bbs/Steam/M.1199354210.A.7E7.html]
[0826 03:37:54][除錯] PostMoney [0]
[0826 03:37:54][除錯] ListDate [1/03]
[0826 03:37:54][除錯] 送出訊息 [b'\r\r\x0c']
--------------------------------------------------
 作者  Siu                                                     看板  C-Strike
 標題  [公告] C-Strike 板 開始賭博!
 時間  Thu Jan  3 17:56:49 2008
───────────────────────────────────────

[測試]1月5日的比賽
請到 C-Strike 板 按'f'參與賭博!

一張 50 Ptt幣, 這是小賭式的賭博
賭盤結束時間: 01/05/2008 21:54:59 Sat
→ Siu:網址在4496篇                                                01/03 18:04
推 Star123:我每個都買一百張了XDDDDDDDDDD                           01/03 19:33
→ QuakeRz:xDDD 不能說我買誰不然違反中壢                           01/03 19:52
推 chatnoir:xDDD 不能說我買誰不然違反桃園                          01/03 20:00
推 cloud6329:xDDD 不能說我買誰不然違反楊梅                         01/
len:685
--------------------------------------------------
--------------------------------------------------
 作者  Siu                                                     看板  C-Strike
 標題  [公告] C-Strike 板 開始賭博!
 時間  Thu Jan  3 17:56:49 2008
───────────────────────────────────────

[測試]1月5日的比賽
請到 C-Strike 板 按'f'參與賭博!

一張 50 Ptt幣, 這是小賭式的賭博
賭盤結束時間: 01/05/2008 21:54:59 Sat
→ Siu:網址在4496篇                                                01/03 18:04
推 Star123:我每個都買一百張了XDDDDDDDDDD                           01/03 19:33
→ QuakeRz:xDDD 不能說我買誰不然違反中壢                           01/03 19:52
推 chatnoir:xDDD 不能說我買誰不然違反桃園                          01/03 20:00
推 cloud6329:xDDD 不能說我買誰不然違反楊梅                         01/03 23:06
推 ncr1126:xDDD 不能說我買誰不然違反新竹                           01/03 23:36
推 LieTo:  xDDD 不能說我買誰不然違反中和                           01/05 13:21
推 Star123:xDDD 不能說我買誰不然違反批踢                           01/05 14:13





  瀏覽 第 1/1 頁 (100%)  目前顯示: 第 01~17 行  (y)回應(X%)推文(h)說明(←)離開
len:957
--------------------------------------------------
[0826 03:37:54][除錯] 批踢踢訊息 [瀏覽文章完成]
[0826 03:37:54][除錯] 花費時間 [0.07]
[0826 03:37:54][除錯] 作者 [Siu              看板 C-Strike]
[0826 03:37:54][除錯] 標題 [[公告] C-Strike 板 開始賭博!]
[0826 03:37:54][除錯] 日期 [Thu Jan 3 17:56:49 2008]
Traceback (most recent call last):
  File "c:\Users\et841\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\et841\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\et841\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\et841\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\et841\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\et841\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\workeara\game\PttSteamCrawler\PTTLibrary_test.py", line 31, in <module>
    PostIndex=4444
  File "C:\Users\et841\.virtualenvs\PttSteamCrawler-wCWn5R4I\lib\site-packages\PTTLibrary\Synchronize.py", line 11, in inner_wrapper
    return f(*args, **kwargs)
  File "C:\Users\et841\.virtualenvs\PttSteamCrawler-wCWn5R4I\lib\site-packages\PTTLibrary\PTT.py", line 491, in getPost
    SearchCondition
  File "C:\Users\et841\.virtualenvs\PttSteamCrawler-wCWn5R4I\lib\site-packages\PTTLibrary\PTT.py", line 960, in _getPost
    IP=IP,
UnboundLocalError: local variable 'IP' referenced before assignment
```

**Comment by Truth0906** [comment]
基本上不考慮編輯過後的文章，因為編輯後想怎麼改都可以，不太可能一個案例一個案例的去修。

**Comment by et84121** [comment]
也許可以讓 post 的 Status 設為 unable to parse
而不是讓爬文中斷？

**Comment by et84121** [comment]
那可能需要做個 `Unable to parse 例外`讓 user 決定要怎麼處理那篇文章？

**Comment by Truth0906** [comment]
目前是會紀錄到錯誤清單裡，讓使用者全部爬完再處理

**Comment by et84121** [comment]
感謝作者的修正 😃
