### ISSUE TITLE
退註帳號登入後查詢使用者會無法取得使用者

### ISSUE THREAD

**Issue by mujay** [Truth0906/PTTLibrary#42]
部分code如下
```
PTTBot.login(username, password, KickOtherLogin=True)
User = pttBot.getUser(username)
```

**Comment by Truth0906** [comment]
可以把 log level 調整成 TRACE，給我看一下嗎?

**Comment by mujay** [comment]
```
[0904 18:15:54][資訊] 繁體中文語言模組 [初始化]
[0904 18:15:54][資訊] 連線核心 [初始化]
[0904 18:15:54][資訊] 批踢踢函式庫 v 0.8.11 [初始化]
[0904 18:15:54][資訊] 繁體中文語言模組 [初始化]
[0904 18:15:54][資訊] 連線核心 [初始化]
[0904 18:15:54][資訊] 批踢踢函式庫 v 0.8.11 [初始化]
[0904 18:15:54][資訊] 登入帳號 [{{username}}]
[0904 18:15:54][資訊] 連線核心 [啟動]
[0904 18:15:54][資訊] 連線批踢踢 [WebSocket]
[0904 18:15:54][除錯] 送出訊息 [隱藏敏感資訊]
--------------------------------------------------
HTTP/1.1 200 OK

     ˙      PTT                   ◣          ˙      ◢██████◤
             140.112.172.11      ◢█◥█◤            ◢█████
  ┌─┐     批踢踢實業坊        ◢▃██◥█◤      ◢█████◤  
  │–└┐   ptt.cc            ◢█████◥█◤    ◢█████
  │–  │                   ◢███◤███◥◤  ◢█████◤  ˙  
─┘    │┌──┐         ◥◤      ████◣◢████    
        └┤  –│                 ◢████◢███◤            
                │┌───┐         █████▇▇▆▆▅▅▄▄▃▂▁
            ┌─┴┘––  └ ◢█████▇▇▆▆▅▅▄▄▃▃▂▂▁
            │––           ◥██
len:496
--------------------------------------------------
--------------------------------------------------

◢                              ◣     ◢█◣ ◢◣◣ ◢█◣ ◢█◣ ◢
                                       █  █ ███ █     █▄▄ █
    第三十屆批踢踢小天使招生中         ███ ███ █  ◣ █     █
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉       ◥  ◤ ◥◥◤ ◥█◤ ◥█◤ ◥█◣
         報名資格：               
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊         ╭─╮            ╭─╮
    註冊滿一年，文章數滿三百篇           │˙│            │˙│
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉         ╰─╯
len:359
--------------------------------------------------
--------------------------------------------------

◢                              ◣     ◢█◣ ◢◣◣ ◢█◣ ◢█◣ ◢
                                       █  █ ███ █     █▄▄ █
    第三十屆批踢踢小天使招生中         ███ ███ █  ◣ █     █
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉       ◥  ◤ ◥◥◤ ◥█◤ ◥█◤ ◥█◣
         報名資格：               
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊         ╭─╮            ╭─╮
    註冊滿一年，文章數滿三百篇           │˙│            │˙│
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉         ╰─╯            ╰─╯
  或註冊滿兩年，文章數滿150篇 ▄▅◣     ◥██◤◥██◤◥██◤    ◢▆▄
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉ ◢████◣    ◥◤    ◥◤    ◥◤   ◢████◣
  且劣文數兩篇以下（含^  ◢█╱  "   █ ◢◣    ◢◣    ◢◣    " █╲█◣
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊ ◢    ∕/ █◤◢██◣◢██◣◢██◣◥  \﹨  ██◣
                           ◢█/ ██◤  ╲                         ◥█ \ █◣
◥                          ◢██◤       ╲                           ◥██◣
                              ◤                                            ◥
                     9/01 ~ 9/14                ╱      ｜
=PTT=[1;30;4
len:856
--------------------------------------------------
--------------------------------------------------

◢                              ◣     ◢█◣ ◢◣◣ ◢█◣ ◢█◣ ◢
                                       █  █ ███ █     █▄▄ █
    第三十屆批踢踢小天使招生中         ███ ███ █  ◣ █     █
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉       ◥  ◤ ◥◥◤ ◥█◤ ◥█◤ ◥█◣
         報名資格：               
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊         ╭─╮            ╭─╮
    註冊滿一年，文章數滿三百篇           │˙│            │˙│
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉         ╰─╯            ╰─╯
  或註冊滿兩年，文章數滿150篇 ▄▅◣     ◥██◤◥██◤◥██◤    ◢▆▄
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉ ◢████◣    ◥◤    ◥◤    ◥◤   ◢████◣
  且劣文數兩篇以下（含^  ◢█╱  "   █ ◢◣    ◢◣    ◢◣    " █╲█◣
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊ ◢    ∕/ █◤◢██◣◢██◣◢██◣◥  \﹨  ██◣
                           ◢█/ ██◤  ╲                         ◥█ \ █◣
◥                          ◢██◤       ╲                           ◥██◣
                              ◤                                            ◥
                     9/01 ~ 9/14                ╱      ｜
ψghostXDD                 請至NewAngels板報名  ╲      ｜
歡迎來到 批踢踢實業坊 目前共有【33333】位使用者想當小天使



 ※本站目前暫停開放新帳號註冊。
=PTT=[21;1H 
len:960
--------------------------------------------------
--------------------------------------------------

◢                              ◣     ◢█◣ ◢◣◣ ◢█◣ ◢█◣ ◢
                                       █  █ ███ █     █▄▄ █
    第三十屆批踢踢小天使招生中         ███ ███ █  ◣ █     █
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉       ◥  ◤ ◥◥◤ ◥█◤ ◥█◤ ◥█◣
         報名資格：               
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊         ╭─╮            ╭─╮
    註冊滿一年，文章數滿三百篇           │˙│            │˙│
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉         ╰─╯            ╰─╯
  或註冊滿兩年，文章數滿150篇 ▄▅◣     ◥██◤◥██◤◥██◤    ◢▆▄
  ﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉ ◢████◣    ◥◤    ◥◤    ◥◤   ◢████◣
  且劣文數兩篇以下（含^  ◢█╱  "   █ ◢◣    ◢◣    ◢◣    " █╲█◣
  ﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊﹉﹊ ◢    ∕/ █◤◢██◣◢██◣◢██◣◥  \﹨  ██◣
                           ◢█/ ██◤  ╲                         ◥█ \ █◣
◥                          ◢██◤       ╲                           ◥██◣
                              ◤                                            ◥
                     9/01 ~ 9/14                ╱      ｜
ψghostXDD                 請至NewAngels板報名  ╲      ｜
歡迎來到 批踢踢實業坊 目前共有【33333】位使用者想當小天使



 ※本站目前暫停開放新帳號註冊。
=PTT=[21;1H

len:960
--------------------------------------------------
--------------------------------------------------






















 登入中，請稍候...
len:33
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [登入中，請稍候]
[0904 18:15:55][除錯] 花費時間 [0.13]
[0904 18:15:55][除錯] 送出訊息 [b'\x0c']
--------------------------------------------------
正在更新與同步線上使用者及好友名單，系統負荷量大時會需時較久...

len:34
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [更新與同步線上使用者及好友名單]
[0904 18:15:55][除錯] 花費時間 [0.05]
[0904 18:15:55][除錯] 送出訊息 [b'\x0c']
--------------------------------------------------






















 正在更新與同步線上使用者及好友名單，系統負荷量大時會需時較久...

len:57
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [更新與同步線上使用者及好友名單]
[0904 18:15:55][除錯] 花費時間 [0.0]
[0904 18:15:55][除錯] 送出訊息 [b'\x0c']
--------------------------------------------------




















       歡迎您再度拜訪，上次您是從 3.90.53.102 連往本站。


 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄  
len:103
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [請按任意鍵繼續]
[0904 18:15:55][除錯] 花費時間 [0.0]
[0904 18:15:55][除錯] 送出訊息 [b'q']
--------------------------------------------------




















       歡迎您再度拜訪，上次您是從 3.90.53.102 連往本站。


 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄  
len:103
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [請按任意鍵繼續]
[0904 18:15:55][除錯] 花費時間 [0.0]
[0904 18:15:55][除錯] 送出訊息 [b'q']
--------------------------------------------------




















       歡迎您再度拜訪，上次您是從 3.90.53.102 連往本站。


 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄  
len:103
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [請按任意鍵繼續]
[0904 18:15:55][除錯] 花費時間 [0.0]
[0904 18:15:55][除錯] 送出訊息 [b'q']
--------------------------------------------------
【 註冊單尚在處理中 】


    您的註冊申請單尚在處理中(處理順位: 2602)，請耐心等候

    * 如果您之前曾使用 email 等認證方式通過註冊認證但又看到此訊息，
      代表您的認證由於資料不完整已被取消 (由於建立新看板的流程中
       有驗證板主註冊資料的程序，若您最近有申請開新看板中則屬此項)

    * 如果您已收到註冊碼卻看到這個畫面，代表您在使用 Email 註冊後
      又另外申請了站長直接人工審核的註冊申請單。
      進入人工審核程序後 Email 註冊碼自動失效，要等到審核完成
       (會多花很多時間，數天到數週是正常的) ，所以請耐心等候。










  ◆ 您的註冊申請單尚在處理中                                    [按任意鍵繼續] 
len:382
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [請按任意鍵繼續]
[0904 18:15:55][除錯] 花費時間 [0.0]
[0904 18:15:55][除錯] 送出訊息 [b'q']
--------------------------------------------------
【主功能表】                     批踢踢實業坊                                  
███████████████████████████████████████
▅▆▆◥███████████████████████████████████
     -─`     ￣￣￣      ￣￣￣    ￣￣                  ￣￣￣￣￣￣        
            ▂▃     ︱       ｜        ﹨     ｜     \                   ∣  
 \_   ∕ ◤▂ ▊。   /  ∕  ﹍ ﹨  L_         |        |  ⊥       ｜   .∠   
   ╳    ▊˙▎◤▎`┐ │,   ︳▁   ╓-.︿   ∕  ` _︳ ∣ .  _x_    \   ｜ ╲ 
 L  _▄▊\ ▆'     N ＼_7_︷-+┤ ↖╳   〉┬'┌‵√ 7╴.-！′   `┬+┼=.∕= ╴
┤ ▄ ▄, ╲,_  ◢│\_╱▏\_∕_﹀  _;}—L  ↘_〕-_╳  |   ＼__F ↙  ﹍] ▏_∕ 
 ╲r=PTT=[
len:542
--------------------------------------------------
--------------------------------------------------
【主功能表】                     批踢踢實業坊                                  
███████████████████████████████████████
▅▆▆◥███████████████████████████████████
     -─`     ￣￣￣      ￣￣￣    ￣￣                  ￣￣￣￣￣￣        
            ▂▃     ︱       ｜        ﹨     ｜     \                   ∣  
 \_   ∕ ◤▂ ▊。   /  ∕  ﹍ ﹨  L_         |        |  ⊥       ｜   .∠   
   ╳    ▊˙▎◤▎`┐ │,   ︳▁   ╓-.︿   ∕  ` _︳ ∣ .  _x_    \   ｜ ╲ 
 L  _▄▊\ ▆'     N ＼_7_︷-+┤ ↖╳   〉┬'┌‵√ 7╴.-！′   `┬+┼=.∕= ╴
┤ ▄ ▄, ╲,_  ◢│\_╱▏\_∕_﹀  _;}—L  ↘_〕-_╳  |   ＼__F ↙  ﹍] ▏_∕ 
 ╲r▎◥〃└_▄〞↗╳ ▕_ ┘╳ ╲_↙▎↙↑_▕  ,┼▕  ﹨  ﹀`  ▎`￣  ↖￣} ╲
 r┘ ▄ ◥▃▆┬╝└ ▎  ╲ ` ▏├  ￣\  ’︺▏可不可以偶爾下雨不必永遠晴天...

                       (A)nnounce     【 精華公佈欄 】
                       (F)avorite     【 我 的 最愛 】
                     > (C)lass        【 分組討論區 】
                       (M)ail         【 私人信件區 】
                       (U)ser         【 個人設定區 】
                       (X)yz          【 系統資訊區 】
                       (G)oodbye         離開，再見…




[9/4 星期三 18:15] [ 魔羯時 ]    線上83916人, 我是{{username}}           [呼叫器]打開 
                     
len:1061
--------------------------------------------------
[0904 18:15:55][資訊] 批踢踢訊息 [登入成功]
[0904 18:15:55][除錯] 花費時間 [0.03]
[0904 18:15:55][資訊] 登入成功
[0904 18:15:55][除錯] 送出訊息 [b' \x1bOD\x1bOD\x1bOD\x1bOD\x1bODT\rQ\r{{username}}\r\x0c']
--------------------------------------------------
【精華文章】                   ★ 分類看板精華區                               
    編號    標      題                                  編    選      日    期
> 《精華區》尚在吸取天地間的日月精華中... :)




















 【已標記(複製) 1 項】 (c)標記/複製 - 無管理權限，無法貼上                      =PTT=[3;1H
len:252
--------------------------------------------------
[0904 18:15:58][除錯] OriScreen [【精華文章】     ★ 分類看板精華區        
 編號 標  題         編 選  日 期
> 《精華區》尚在吸取天地間的日月精華中... :)




















 【已標記(複製) 1 項】 (c)標記/複製 - 無管理權限，無法貼上      =PTT=[3;1H]
尚在吸取天地間的日月精華中... :)
1
Traceback (most recent call last):
  File "single_account_login.py", line 33, in <module>
    main()
  File "single_account_login.py", line 25, in main
    updateAccountInfo(username, PTTBot)
  File "/Users/james/Documents/site-project/ptt_auto_login/ptt_auto_login.py", line 72, in updateAccountInfo
    User = pttBot.getUser(username)
  File "/usr/local/lib/python3.7/site-packages/PTTLibrary/Synchronize.py", line 11, in inner_wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/PTTLibrary/PTT.py", line 1788, in getUser
    return self._getUser(UserID)
  File "/usr/local/lib/python3.7/site-packages/PTTLibrary/PTT.py", line 1733, in _getUser
    raise Exceptions.ParseError(OriScreen)
PTTLibrary.Exceptions.ParseError: 【精華文章】                   ★ 分類看板精華區                               
    編號    標      題                                  編    選      日    期
> 《精華區》尚在吸取天地間的日月精華中... :)




















 【已標記(複製) 1 項】 (c)標記/複製 - 無管理權限，無法貼上                      =PTT=[3;1H
```

已刪除個人資料

**Comment by Truth0906** [comment]
目前看起來，退註帳號沒辦法存取使用者清單，已經把一些應該會被擋掉的功能加上 API 偵測。

以後會直接跳出未註冊使用者的例外

**Comment by Truth0906** [comment]
更新囉 試試看
